### ISSUE TITLE
playback crash

### ISSUE THREAD

**Issue by dga4130-renato** [dmitrylyzo/jellyfin-tizen#5]
Video
TitleSD MPEG4
CodecMPEG4
Tag codecXVID
ProfiloAdvanced Simple Profile
Livello5
Risoluzione656x272
Formato2.40:1
InterlacciatoNo
Framerate23.976
Bitrate1139 kbps
Formato Pixelyuv420p
Ref frame1
Audio
TitleDolby Digital 5.1
CodecAC3
disposizione5.1
Canali6 ch
Bitrate384 kbps
frequenza di campion.48000 Hz
PredefinitoNo
BDRip.XviD.avi
Dimensione1066 MB
this crashes the app.. black screen and have to press app home or switch tv off

**Comment by dga4130-renato** [comment]
every mpeg4 container crashes, black screen... if you press retun untill a request box says, exit, then exit and reopen the app gives you the main screen back.
in ex. h264 h 265 works well.

**Comment by dmitrylyzo** [comment]
What TV you have?

I can reproduce this issue on my TV (UE65NU7400). It seems that new (_2018+?_) Samsung TV don't support XViD/DivX.
You can verify this by running the same video file from USB-Flash.

If so, then we should tweak device profile to enable transcoding of such format.

**Comment by dga4130-renato** [comment]
UE50RU7090UXZT

**Comment by dga4130-renato** [comment]
is it possible to fix this ? i mean is it a change on the code or a setting ?

**Comment by dga4130-renato** [comment]
working now thanks !
